// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: demo_hxd8357d

#include "ui.h"
#include "sl_si91x_rgb_led_config.h"
#include "sl_si91x_rgb_led_instances.h"
#include "sl_si91x_rgb_led.h"

static volatile bool led0_status = false;
static volatile bool led1_status = false;

void led0_switch(lv_event_t *e)
{
  (void) e;
  // Your code here
  if (!lv_obj_has_state(ui_led0Switch, LV_STATE_CHECKED)) {
    led0_status = false;
    sl_si91x_rgb_led_off(led_led0.blue);
    sl_si91x_rgb_led_off(led_led0.green);
    lv_obj_add_flag(ui_led0ONSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_led0OnLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led0OffSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led0OffLabel, LV_OBJ_FLAG_HIDDEN);
  } else {
    led0_status = true;
    sl_si91x_rgb_led_on(led_led0.blue);
    sl_si91x_rgb_led_off(led_led0.green);
    lv_obj_add_flag(ui_led0OffSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_led0OffLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led0ONSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led0OnLabel, LV_OBJ_FLAG_HIDDEN);
  }
}

void led1_switch(lv_event_t *e)
{
  (void) e;
  // Your code here
  if (!lv_obj_has_state(ui_led1Switch, LV_STATE_CHECKED)) {
    led1_status = false;
    sl_si91x_rgb_led_off(led_led0.red);
    sl_si91x_rgb_led_off(led_led0.green);
    lv_obj_add_flag(ui_led1ONSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_led1OnLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led1OffSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led1OffLabel, LV_OBJ_FLAG_HIDDEN);
  } else {
    led1_status = true;
    sl_si91x_rgb_led_on(led_led0.red);
    sl_si91x_rgb_led_off(led_led0.green);
    lv_obj_add_flag(ui_led1OffSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_led1OffLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led1ONSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led1OnLabel, LV_OBJ_FLAG_HIDDEN);
  }
}
