name: Check-Code-Convention

on:
  pull_request_target:
    types: [opened, synchronize, edited]

env:
  WORKSPACE: ${{ github.workspace }}

jobs:
  coding_convention:
    runs-on: ubuntu-latest
    steps:
    - name: Create GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Checkout code repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository  }}
        token: ${{ steps.app-token.outputs.token }}
        path: 'projects'

    - name: Checkout tools repository
      uses: actions/checkout@v4
      with:
        repository: SiliconLabsSoftware/aep_ci_tools
        ref: 'pr_checking'
        token: ${{ steps.app-token.outputs.token }}
        path: 'aep_ci_tools'

    - name: Check the changes
      id: pr_check
      run: |
        echo ${{ github.base_ref }}

        cd projects
        bash ${{ github.workspace }}/aep_ci_tools/tphd_scripts/third_party_check_changed_projects.sh \
        ${{ github.base_ref }} ${{ github.event.pull_request.number }}
        
        if [ ! -f  $WORKSPACE/changed_projects.txt ] || [ ! -s  $WORKSPACE/changed_projects.txt ]; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "No project changes detected...........Skipped"
          exit 0
        fi
        echo "has_changes=true" >> $GITHUB_OUTPUT
        echo "...........Changed projects:..........."
        cat $WORKSPACE/changed_projects.txt

    - name: Run test
      if: ${{ steps.pr_check.outputs.has_changes == 'true' }}
      run : |
        cd projects
        xargs -I{} -a $WORKSPACE/changed_projects.txt find {} -type f -name "*.[ch]" > source_list.txt
        bash ${{ github.workspace }}/aep_ci_tools/scripts/check_coding_style.sh source_list.txt > coding_style_report.html
        
    - name: Upload Result
      id: html_report
      if: ${{ steps.pr_check.outputs.has_changes == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: coding_style_report
        path: projects/coding_style_report.html
        retention-days: 90

    - name: Browse the formatted files by Uncrustify
      id: solution_report
      if: ${{ steps.pr_check.outputs.has_changes == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: uncrustify_formatted_files
        path: projects/uncrustify_formatted_files.zip
        if-no-files-found: ignore

    - name: Check log file to set status of the job
      if: ${{ steps.pr_check.outputs.has_changes == 'true' }}
      run: |
        cd projects
        echo "Check report here: ${{ steps.html_report.outputs.artifact-url }}"
        if grep -qe "failed" coding_style_report.html; then
          echo "Result: Failure"
          echo "Check Solution here: ${{ steps.solution_report.outputs.artifact-url }}"
          exit 1
        else
          echo "Result: Success"
        fi